<?php

/**
 * @file
 *
 * This module add versioning information to projects checked out of git.
 */

/**
 * Implement hook_system_info_alter() to provide metadata to drupal from git.
 *
 * We support populating $info['version'] and $info['project'].
 *
 * @param $info
 *   The module/theme info array we're altering.
 * @param $file
 *   An object describing the filesystem location of the module/theme.
 * @param $type
 *   Can be module or theme.
 */
function git_deploy_system_info_alter(&$info, $file, $type = NULL) {
  if (empty($info['version'])) {
    $directory = dirname($file->uri);
    // Check whether this belongs to core. Speed optimization.
    if (substr($directory, 0, strlen($type)) != $type) {
      while ($directory && !is_dir("$directory/.git")) {
        $directory = substr($directory, 0,  strrpos($directory, '/'));
      }
      $git_dir = "$directory/.git";
      // Theoretically /.git could exist.
      if ($directory && is_dir($git_dir)) {
        $git_config = file_get_contents($git_dir . '/config');
        if (preg_match(';^\s*url\s*=\s*.*?([^/.]+?)(\.git)?\s*$;m', $git_config, $matches)) {
          $info['project'] = $matches[1];
        }
        // No need to initalize this variable because it is taken by reference.
        exec("git  --git-dir $git_dir rev-list --topo-order --max-count=1 HEAD", $last_tag_hash);
        if ($last_tag_hash) {
          exec("git --git-dir $git_dir describe  --tags $last_tag_hash[0]", $last_tag);
          if ($last_tag) {
            $last_tag = $last_tag[0];
            if (preg_match('/^(' . preg_quote(DRUPAL_CORE_COMPATIBILITY) . '-\d+\.\d+(?:-[^-]+)?)(-(\d+-)g[0-9a-f]{7})?$/', $last_tag, $matches)) {
              $info['version'] = isset($matches[2]) ? $matches[1] . '.' . $matches[3] . 'dev' : $last_tag;
            }
          }
        }
      }
    }
  }
}
