<?php

/**
 * @file
 *
 * This module provides metadata about modules installed via git for
 * Drupal's updates listing. As it is intended to provide the same
 * functionality as cvs_deploy but for git modules, this module is modeled
 * after cvs_deploy which is written by Derek Wright ("dww")
 * http://drupal.org/user/46549.
 *
 * The intention of this module is to add versioning information to projects
 * checked out of git.
 */

/**
 * Implement hook_system_info_alter() to provide metadata to drupal
 *   from git.
 *
 * We support populating $info['version'] and $info['project'], as
 * cvs_deploy does.
 *
 * @param $info
 *   The module/theme info array we're altering.
 * @param $file
 *   An object describing the filesystem location of the module/theme.
 * @param $type
 *   Can be module or theme.
 */
function git_deploy_system_info_alter(&$info, $file, $type = NULL) {
  if (empty($info['version'])) {
    $config = conf_path();
    $profile = drupal_get_profile();
    $stopdirs["profiles/$profile/$type"] = TRUE;
    $stopdirs["sites/all/$type"] = TRUE;
    $stopdirs["$config/$type"] = TRUE;
    $directory = dirname($file->uri);
    // Check whether this belongs to core.
    if (substr($directory, 0, strlen($type)) != $type) {
      // Theoretically $directory can never be empty but it's better to make
      // sure we are falling into an infite loop.
      while ($directory && !isset($stopdirs[$directory]) && !is_dir("$directory/.git")) {
        $directory = substr($directory, 0,  strrpos($directory, '/'));
      }
      if (is_dir("$directory/.git")) {
        $git_dir = "$directory/.git";
        // No need to initalize this variable because it is taken by reference.
        exec("git  --git-dir $git_dir rev-list --topo-order --max-count=1 HEAD", $last_tag_hash);
        if ($last_tag_hash) {
          exec("git --git-dir $git_dir describe  --tags $last_tag_hash[0]", $last_tag);
          if ($last_tag) {
            $last_tag = $last_tag[0];
            if (preg_match('/^(' . preg_quote(DRUPAL_CORE_COMPATIBILITY) . '-\d+\.\d+(?:-[^-]+)?)(-(\d+-)g[0-9a-f]{7})?$/', $last_tag, $matches)) {
              $info['version'] = isset($matches[2]) ? $matches[1] . '.' . $matches[3] . 'dev' : $last_tag;
            }
          }
        }
      }
    }
  }
}
